replicaCount: 2

image:
  repository: ghcr.io/daniil-dyachenko/ecommerce-app
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi